### ISSUE TITLE
Thread main panicked

### ISSUE THREAD

**Issue by miguelccoelho** [wiiznokes/fan-control#108] opened 2024-05-05 12:18 UTC
#### Bug Description:
When I try to run the fan-control command, the following error shows, and the app is never launched:
`thread 'main' panicked at /run/build/fan-control/cargo/vendor/iced_tiny_skia/src/window/compositor.rs:56:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x77 does not use softbuffer's pixel format and is unsupported"), None)
`

#### Expected Result:
Applications should run

#### Steps to Reproduce:
> flatpak install --user https://flathub.org/repo/appstream/io.github.wiiznokes.fan-control.flatpakref
> cat /etc/udev/rules.d/60-fan-control.rules

KERNEL=="hwmon7", SUBSYSTEM=="hwmon", TAG+="uaccess"
> /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=fan-control io.github.wiiznokes.fan-control
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
thread 'main' panicked at /run/build/fan-control/cargo/vendor/iced_tiny_skia/src/window/compositor.rs:56:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x77 does not use softbuffer's pixel format and is unsupported"), None)

#### Possible Additional Information:
I've run the command on a terminal, with sudo -i first, to make sure that it has access to write anywhere

#### Operating system
Linux 6.6.26-1-MANJARO x86_64

#### fan-control version
0.1.3

#### Logs, Panic Messages, Stack Traces:
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
thread 'main' panicked at /run/build/fan-control/cargo/vendor/iced_tiny_skia/src/window/compositor.rs:56:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x77 does not use softbuffer's pixel format and is unsupported"), None)
stack backtrace:
   0:           0xde3ba6 - <unknown>
   1:           0xe12460 - <unknown>
   2:           0xddfd8f - <unknown>
   3:           0xde3984 - <unknown>
   4:           0xde5207 - <unknown>
   5:           0xde4f69 - <unknown>
   6:           0xde5698 - <unknown>
   7:           0xde5572 - <unknown>
   8:           0xde40a6 - <unknown>
   9:           0xde52c4 - <unknown>
  10:           0x44b455 - <unknown>
  11:           0x44b9a3 - <unknown>
  12:           0x4c99f8 - <unknown>
  13:           0x4a7806 - <unknown>
  14:           0x4a8a3d - <unknown>
  15:           0x4621e9 - <unknown>
  16:           0x52ebe3 - <unknown>
  17:           0x51dee9 - <unknown>
  18:           0xdd5e31 - <unknown>
  19:           0x462b25 - <unknown>
  20:     0x7ffa09ec808a - <unknown>
  21:     0x7ffa09ec814b - __libc_start_main
  22:           0x44c0b5 - <unknown>
  23:                0x0 - <unknown>

**Comment by wiiznokes** [comment] 2024-05-05 13:31
Closing as duplicate of #98.

> I've run the command on a terminal, with sudo -i first, to make sure that it has access to write anywhere

This is no longer necessary thanks to udev rules. The app run fine without sudo permission

**Closed by wiiznokes** 2024-05-05 13:31 UTC
Labels: bug
